# Generated by Django 4.2.19 on 2025-03-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Menu categories",
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                ("menu_id", models.AutoField(primary_key=True, serialize=False)),
                ("principal", models.CharField(max_length=100)),
                ("extra1", models.CharField(max_length=100)),
                ("extra2", models.CharField(max_length=100)),
                ("extra3", models.CharField(max_length=100)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="menus",
                        to="pages.menucategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Menus",
            },
        ),
    ]
