# Generated by Django 4.2.19 on 2025-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("breakfast_servings", models.PositiveIntegerField(default=200)),
                ("lunch_servings", models.PositiveIntegerField(default=1000)),
                ("dinner_servings", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breakfast_drinks",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"category__meal_type": "DRINK"},
                        related_name="breakfast_drink_days",
                        to="pages.menu",
                    ),
                ),
                (
                    "breakfast_meals",
                    models.ManyToManyField(
                        blank=True, related_name="breakfast_days", to="pages.menu"
                    ),
                ),
                (
                    "dinner_drinks",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"category__meal_type": "DRINK"},
                        related_name="dinner_drink_days",
                        to="pages.menu",
                    ),
                ),
                (
                    "dinner_meals",
                    models.ManyToManyField(
                        blank=True, related_name="dinner_days", to="pages.menu"
                    ),
                ),
                (
                    "lunch_drinks",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"category__meal_type": "DRINK"},
                        related_name="lunch_drink_days",
                        to="pages.menu",
                    ),
                ),
                (
                    "lunch_meals",
                    models.ManyToManyField(
                        blank=True, related_name="lunch_days", to="pages.menu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Menu",
                "verbose_name_plural": "Daily Menus",
                "ordering": ["-date"],
            },
        ),
    ]
