# Generated by Django 4.2.19 on 2025-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_dailymenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BF", "Desayuno"),
                            ("LN", "Almuerzo"),
                            ("DN", "Cena"),
                        ],
                        max_length=2,
                    ),
                ),
                ("servings", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "drinks",
                    models.ManyToManyField(
                        blank=True, related_name="daily_drinks", to="pages.menu"
                    ),
                ),
                (
                    "meals",
                    models.ManyToManyField(
                        blank=True, related_name="daily_meals", to="pages.menu"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Meal",
                "verbose_name_plural": "Daily Meals",
                "ordering": ["-date", "meal_type"],
                "unique_together": {("date", "meal_type")},
            },
        ),
        migrations.DeleteModel(
            name="DailyMenu",
        ),
    ]
