# Generated by Django 4.2.19 on 2025-03-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_dailymeal_delete_dailymenu"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("breakfast_meals", models.JSONField(blank=True, null=True)),
                ("breakfast_servings", models.PositiveIntegerField(default=200)),
                ("lunch_meals", models.JSONField(blank=True, null=True)),
                ("lunch_servings", models.PositiveIntegerField(default=1000)),
                ("dinner_meals", models.JSONField(blank=True, null=True)),
                ("dinner_servings", models.PositiveIntegerField(default=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "breakfast_drink",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="breakfast_drinks",
                        to="pages.menu",
                    ),
                ),
                (
                    "dinner_drink",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dinner_drinks",
                        to="pages.menu",
                    ),
                ),
                (
                    "lunch_drink",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lunch_drinks",
                        to="pages.menu",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Menu",
                "verbose_name_plural": "Daily Menus",
                "ordering": ["-date"],
            },
        ),
        migrations.DeleteModel(
            name="DailyMeal",
        ),
    ]
